# Generated by Django 5.1.3 on 2024-11-30 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('shareable_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
